version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Git installation
          command: apt-get -qq update; apt-get -y install git
      - run: 
          name: install tzdata
          command: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
      - run:
          name: Latex installation
          command: apt-get -qq update && apt-get install -y --no-install-recommends latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-xetex texlive-pictures texlive-lang-french lmodern fonts-font-awesome
          environment: 
            TZ: America/Toronto
      - add_ssh_keys
      - checkout
      - run:
          name: Build the PDF
          command: cd example && latexmk -cd -f -lualatex -interaction=nonstopmode -synctex=1 cv.tex
      - store_artifacts:
          path: ~/project/example/cv.pdf
      - run:
          name: Move file
          command: |
            mv ~/project/example/cv.pdf ./resume.pdf
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "maxpham99@gmail.com"
            git config user.name "CircleCI Job"
            git checkout master
            git commit --allow-empty -am "Updated new resume from CircleCI [skip ci]"
            git push origin master
